apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task
spec:
  params:
    - name: pipeline-name
      type: string
  steps:
    - name: sleep2mins
      image: ubuntu
      script: |
        PIPELINE_NAME=$(params.pipeline-name)
        echo "Pipeline name is $PIPELINE_NAME"
