apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  tasks:
    - name: pipeline-hello-task
      taskRef:
        name: hello-task
   - name: pipeline-hello-task
      taskRef:
        name: hello-task2
