apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
    - name: shouldcontinue
      image: ubuntu
      onError: continue
      script: |
         exit 1
    - name: echo3
      image: ubuntu
      onError: continue
      command:
        - echo
      args:
        - "hello world3"
