apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
    - name: echo2
      image: ubuntu
      onError: continue
      command:
        - exit 1
    - name: echo3
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
