apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  params:
    - name: pipeline-name
      type: string
  steps:
    - name: sleep2mins
      image: ubuntu
      env:
        - name: PIPELINE_NAME
          value: $(params.pipeline-name)
      script: |
        export PIPELINE_NAME=$(params.pipeline-name)
        echo "Pipeline name is $PIPELINE_NAME"
