apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  params:
    - name: pipeline-name
      type: string
      default: "my-pipeline"
      description: The name of the pipeline
    - name: skip
      type: string
      default: "false"
      description: Whether to skip the task
  tasks:
    - name: pipeline-hello-task3
      taskRef:
        name: hello-task3
    - name: skipped-task
      taskRef:
        name: skipped-task
      when:
        - input: "$(params.skip)"
          operator: in
          values: ["true"]
    - name: pipeline-hello-task2
      taskRef:
        name: hello-task2
