apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
    - name: echo2
      image: ubuntu
      command:
        - exit 1
      args:
        - "hello world2"
    - name: echo2
      image: ubuntu
      command:
        - echo
      args:
        - "hello world2"
